import { act, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { customToolDefaults, validateCustomToolSchema } from '@shared/customTools'
import { CustomToolEditor } from './CustomToolEditor'

vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key }) }))
const validateSchema = vi.fn(async (schema: unknown) => { validateCustomToolSchema(schema) })
beforeEach(() => { vi.clearAllMocks(); vi.stubGlobal('gale', { tools: { validateSchema } }) })
afterEach(() => vi.unstubAllGlobals())
const tool = { ...customToolDefaults, id: 'example', name: 'example', description: 'Example tool',
  inputSchema: { type: 'object', properties: { title: { type: 'string' } } } }
const section = (name: string) => userEvent.click(within(screen.getByRole('radiogroup', { name: 'custom_tools.editor_section' })).getByRole('radio', { name }))
const change = (name: string, value: string) => fireEvent.change(screen.getByRole('textbox', { name }), { target: { value } })

describe('custom tool editor sections', () => {
  it('keeps information and invalid source drafts across sections and saves the corrected values together', async () => {
    const onSave = vi.fn().mockResolvedValue(undefined)
    render(<CustomToolEditor tool={tool} onSave={onSave} onClose={vi.fn()} />)
    expect(screen.queryByRole('button', { name: 'custom_tools.parameter_add' })).not.toBeInTheDocument()
    change('custom_tools.description', 'Revised information')
    await section('custom_tools.parameter_form')
    expect(screen.queryByRole('textbox', { name: 'custom_tools.command' })).not.toBeInTheDocument()
    await userEvent.click(screen.getByRole('radio', { name: 'settings.file_source' }))
    change('custom_tools.schema', '{unfinished')
    await section('custom_tools.information')
    expect(screen.getByRole('textbox', { name: 'custom_tools.description' })).toHaveValue('Revised information')
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(onSave).not.toHaveBeenCalled()
    expect(screen.getByRole('textbox', { name: 'custom_tools.schema' })).toHaveValue('{unfinished')
    change('custom_tools.schema', JSON.stringify({ type: 'object', properties: { count: { type: 'integer' } } }))
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(onSave).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ description: 'Revised information', inputSchema: { type: 'object', properties: { count: { type: 'integer' } } } }))
  })
  it('edits parameters in one dialog, preserves unfinished parameter fields across tabs and requires applying them before save', async () => {
    const onSave = vi.fn().mockResolvedValue(undefined)
    render(<CustomToolEditor tool={tool} initialSection="parameters" onSave={onSave} onClose={vi.fn()} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit title' }))
    expect(screen.getAllByRole('dialog')).toHaveLength(1)
    change('custom_tools.parameter_name', 'heading')
    await section('custom_tools.information')
    change('custom_tools.name', 'renamed_tool')
    expect(screen.getByRole('button', { name: 'common.save' })).toBeDisabled()
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_finish' }))
    expect(screen.getByRole('textbox', { name: 'custom_tools.parameter_name' })).toHaveValue('heading')
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_apply' }))
    expect(onSave).not.toHaveBeenCalled()
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(onSave).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ name: 'renamed_tool', inputSchema: { type: 'object', properties: { heading: { type: 'string' } } } }))
  })
  it('protects unfinished parameter input on Escape and preserves it when discarding is cancelled', async () => {
    const onClose = vi.fn()
    render(<CustomToolEditor tool={tool} initialSection="parameters" onSave={vi.fn()} onClose={onClose} />)
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_add' }))
    change('custom_tools.parameter_name', 'draft_field')
    await userEvent.keyboard('{Escape}')
    expect(onClose).not.toHaveBeenCalled()
    const confirmation = screen.getByRole('alertdialog')
    await userEvent.click(within(confirmation).getByRole('button', { name: 'common.cancel' }))
    expect(screen.getByRole('textbox', { name: 'custom_tools.parameter_name' })).toHaveValue('draft_field')
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_cancel' }))
    await userEvent.click(within(screen.getByRole('alertdialog')).getByRole('button', { name: 'common.confirm' }))
    expect(screen.getByRole('button', { name: 'common.save' })).toBeEnabled()
    await userEvent.click(screen.getByRole('button', { name: 'common.cancel' }))
    expect(onClose).toHaveBeenCalledTimes(1)
  })
  it('asks before discarding information and retains the whole draft after a failed save', async () => {
    const onClose = vi.fn()
    const onSave = vi.fn().mockRejectedValue(new Error('Disk is full'))
    render(<CustomToolEditor tool={tool} onSave={onSave} onClose={onClose} />)
    change('custom_tools.name', 'unsaved_tool')
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Disk is full')
    expect(screen.getByRole('textbox', { name: 'custom_tools.name' })).toHaveValue('unsaved_tool')
    await userEvent.click(screen.getByRole('button', { name: 'common.cancel' }))
    expect(onClose).not.toHaveBeenCalled()
    await userEvent.click(within(screen.getByRole('alertdialog')).getByRole('button', { name: 'common.confirm' }))
    expect(onClose).toHaveBeenCalledTimes(1)
  })
  it('blocks closing, switching and saving during parameter validation, then keeps a rejected draft editable', async () => {
    let reject!: (reason: Error) => void
    validateSchema.mockImplementationOnce(() => new Promise((_resolve, fail) => { reject = fail }))
    const onClose = vi.fn()
    const onSave = vi.fn()
    render(<CustomToolEditor tool={tool} initialSection="parameters" onSave={onSave} onClose={onClose} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit title' }))
    change('custom_tools.parameter_name', 'new_title')
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_apply' }))
    expect(screen.getByRole('button', { name: 'common.save' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'common.cancel' })).toBeDisabled()
    expect(screen.getByRole('radio', { name: 'custom_tools.information' })).toBeDisabled()
    await userEvent.keyboard('{Escape}')
    expect(onClose).not.toHaveBeenCalled()
    await act(async () => reject(new Error('Invalid parameter')))
    expect(screen.getByRole('textbox', { name: 'custom_tools.parameter_name' })).toHaveValue('new_title')
    expect(screen.getByRole('alert')).toHaveTextContent('Invalid parameter')
    expect(onSave).not.toHaveBeenCalled()
  })
})
