import { useState } from 'react'
import { act, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ToolParameters } from './ToolParameters'
import { CustomToolEditor } from './CustomToolEditor'
import { customToolDefaults, validateCustomToolSchema } from '@shared/customTools'
import { notice } from '../notice'

vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key }) }))
vi.mock('../notice', () => ({ notice: { error: vi.fn() } }))
const validateSchema = vi.fn(async (schema: unknown) => { validateCustomToolSchema(schema) })
beforeEach(() => { vi.clearAllMocks(); vi.stubGlobal('gale', { tools: { validateSchema } }) })
afterEach(() => vi.unstubAllGlobals())
function Harness({ schema, changed = () => {} }: { schema: object; changed?(value: string): void }) {
  const [value, setValue] = useState(JSON.stringify(schema))
  return <ToolParameters value={value} onChange={next => { setValue(next); changed(next) }} />
}
const simple = { type: 'object', properties: { title: { type: 'string', description: 'A title', examples: ['sample'] } }, required: ['title'], additionalProperties: false }
async function apply() { await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_apply' })) }
async function source() { await userEvent.click(screen.getByRole('radio', { name: 'settings.file_source' })) }
function sourceValue() { return JSON.parse((screen.getByRole('textbox', { name: 'custom_tools.schema' }) as HTMLTextAreaElement).value) }
function field(name: string, value: string) { fireEvent.change(screen.getByLabelText(name), { target: { value } }) }
async function chooseType(type: string) {
  await userEvent.click(screen.getByRole('combobox', { name: 'custom_tools.parameter_type' }))
  await userEvent.click(screen.getByRole('option', { name: `custom_tools.parameter_type_${type}` }))
}

describe('custom tool parameters', () => {
  it.each(['add', 'rename'])('inherits an independently required name when using %s', async operation => {
    render(<Harness schema={{ type: 'object', properties: { old: { type: 'string' } }, required: ['token'] }} />)
    await userEvent.click(screen.getByText('custom_tools.parameter_constraints'))
    expect(screen.getByText('["token"]')).toBeVisible()
    await userEvent.click(screen.getByRole('button', { name: operation === 'add' ? 'custom_tools.parameter_add' : 'common.edit old' }))
    field('custom_tools.parameter_name', 'token')
    expect(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' })).toBeChecked()
    field('custom_tools.parameter_name', 'unrelated')
    expect(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' })).not.toBeChecked()
    field('custom_tools.parameter_name', 'token')
    await apply()
    await source()
    expect(sourceValue().required).toEqual(['token'])
    expect(sourceValue().properties.token).toEqual({ type: 'string' })
  })
  it('allows an explicit cancellation of the inherited required constraint', async () => {
    render(<Harness schema={{ type: 'object', required: ['token'] }} />)
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_add' }))
    field('custom_tools.parameter_name', 'token')
    expect(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' })).toBeChecked()
    await userEvent.click(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' }))
    await apply()
    await source()
    expect(sourceValue()).toEqual({ type: 'object', properties: { token: { type: 'string' } }, required: [] })
  })
  it.each(['array', 'object'])('does not synthesize constraints when reselecting %s or switching away and back', async type => {
    const schema = { type: 'object', properties: { value: { type } } }
    render(<Harness schema={schema} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit value' }))
    await chooseType(type)
    await apply()
    await source()
    expect(sourceValue()).toEqual(schema)
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.edit value' }))
    await chooseType('string')
    await chooseType(type)
    await apply()
    await source()
    expect(sourceValue()).toEqual(schema)
  })
  it.each([
    { type: 'array', items: { type: 'boolean' }, minItems: 1 },
    { type: 'object', properties: { child: { type: 'string' } }, required: ['child'] }
  ])('hides inactive children after changing $type to string, retaining them for changing back', async original => {
    render(<Harness schema={{ type: 'object', properties: { value: original } }} />)
    const childButton = original.type === 'array' ? 'common.edit custom_tools.parameter_items' : 'common.edit child'
    expect(screen.getByRole('button', { name: childButton })).toBeVisible()
    await userEvent.click(screen.getByRole('button', { name: 'common.edit value' }))
    await chooseType('string')
    await apply()
    expect(screen.queryByRole('button', { name: childButton })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /custom_tools.collapse value|custom_tools.expand value/ })).not.toBeInTheDocument()
    await source()
    expect(sourceValue().properties.value).toEqual({ ...original, type: 'string' })
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.edit value' }))
    await chooseType(original.type)
    await apply()
    expect(screen.getByRole('button', { name: childButton })).toBeVisible()
    await source()
    expect(sourceValue().properties.value).toEqual(original)
  })
  it('leaves a newly chosen array unconstrained until its items are explicitly edited', async () => {
    render(<Harness schema={{ type: 'object', properties: { value: { type: 'string' } } }} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit value' }))
    await chooseType('array')
    await apply()
    await source()
    expect(sourceValue().properties.value).toEqual({ type: 'array' })
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.edit custom_tools.parameter_items' }))
    await chooseType('integer')
    await apply()
    await source()
    expect(sourceValue().properties.value).toEqual({ type: 'array', items: { type: 'integer' } })
  })
  it('displays nested definitions read-only, with the full source accessible', async () => {
    render(<ToolParameters value={JSON.stringify(simple)} />)
    expect(screen.getByText('title')).toBeVisible()
    expect(screen.getByText('A title')).toBeVisible()
    expect(screen.getByText('custom_tools.parameter_required')).toBeVisible()
    expect(screen.queryByRole('button', { name: /common.edit|common.delete|parameter_add/ })).not.toBeInTheDocument()
    await source()
    expect(screen.getByText(JSON.stringify(simple))).toBeVisible()
  })
  it('renames, changes required status, and deletes a parameter without losing metadata', async () => {
    render(<Harness schema={simple} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit title' }))
    field('custom_tools.parameter_name', 'heading')
    field('custom_tools.description', 'Updated title')
    await userEvent.click(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' }))
    await apply()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    await source()
    expect(sourceValue()).toEqual({ ...simple, properties: { heading: { ...simple.properties.title, description: 'Updated title' } }, required: [] })
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.delete heading' }))
    expect(screen.getByText('custom_tools.parameter_empty')).toBeVisible()
    await source()
    expect(sourceValue()).toMatchObject({ properties: {}, required: [], additionalProperties: false })
  })
  it('adds a required child to an object inside array items', async () => {
    const schema = { type: 'object', properties: { rows: { type: 'array', items: { type: 'object', properties: {} } } } }
    render(<Harness schema={schema} />)
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_add custom_tools.parameter_items' }))
    field('custom_tools.parameter_name', 'id')
    await userEvent.click(screen.getByRole('combobox', { name: 'custom_tools.parameter_type' }))
    await userEvent.click(screen.getByRole('option', { name: 'custom_tools.parameter_type_integer' }))
    await userEvent.click(screen.getByRole('checkbox', { name: 'custom_tools.parameter_required' }))
    await userEvent.click(within(screen.getByRole('group', { name: /custom_tools.parameter_(add|edit)$/ })).getByText('custom_tools.parameter_constraints'))
    field('custom_tools.parameter_minimum', '1')
    await apply()
    expect(screen.getByText('id')).toBeVisible()
    await source()
    expect(sourceValue().properties.rows.items).toEqual({ type: 'object', properties: { id: { type: 'integer', minimum: 1 } }, required: ['id'] })
  })
  it('edits unconstrained array items without requiring existing items', async () => {
    render(<Harness schema={{ type: 'object', properties: { rows: { type: 'array' } } }} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit custom_tools.parameter_items' }))
    await userEvent.click(screen.getByRole('combobox', { name: 'custom_tools.parameter_type' }))
    await userEvent.click(screen.getByRole('option', { name: 'custom_tools.parameter_type_boolean' }))
    await apply()
    await source()
    expect(sourceValue().properties.rows.items).toEqual({ type: 'boolean' })
  })
  it('keeps invalid source drafts intact until corrected before switching to the form', async () => {
    render(<Harness schema={simple} />)
    await source()
    field('custom_tools.schema', '{broken')
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    expect(screen.getByRole('radio', { name: 'settings.file_source' })).toBeChecked()
    expect(screen.getByRole('textbox', { name: 'custom_tools.schema' })).toHaveValue('{broken')
    expect(notice.error).toHaveBeenCalled()
    field('custom_tools.schema', JSON.stringify({ ...simple, 'x-extra': { enabled: true } }))
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.edit title' }))
    await apply()
    await source()
    expect(sourceValue()['x-extra']).toEqual({ enabled: true })
  })
  it('accepts decimal and negative constraints as typed, preserving enum and default JSON values', async () => {
    render(<Harness schema={{ type: 'object', properties: { ratio: { type: 'number' } } }} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit ratio' }))
    await userEvent.click(within(screen.getByRole('group', { name: /custom_tools.parameter_(add|edit)$/ })).getByText('custom_tools.parameter_constraints'))
    await userEvent.type(screen.getByRole('spinbutton', { name: 'custom_tools.parameter_minimum' }), '-1.5')
    await userEvent.type(screen.getByRole('spinbutton', { name: 'custom_tools.parameter_multipleOf' }), '0.5')
    field('custom_tools.parameter_enum', '[-1.5,0,1.5]')
    field('custom_tools.parameter_default', '0')
    await apply()
    await source()
    expect(sourceValue().properties.ratio).toEqual({ type: 'number', minimum: -1.5, multipleOf: 0.5, enum: [-1.5, 0, 1.5], default: 0 })
  })
  it('keeps invalid parameter drafts editable and leaves the schema unchanged on cancel', async () => {
    const changed = vi.fn()
    render(<Harness schema={simple} changed={changed} />)
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_add' }))
    field('custom_tools.parameter_name', 'title')
    await apply()
    expect(screen.getByRole('alert')).toHaveTextContent('custom_tools.parameter_name_duplicate')
    field('custom_tools.parameter_name', 'other')
    await userEvent.click(within(screen.getByRole('group', { name: /custom_tools.parameter_(add|edit)$/ })).getByText('custom_tools.parameter_constraints'))
    field('custom_tools.parameter_enum', '"a"')
    await apply()
    expect(screen.getByRole('alert')).toHaveTextContent('custom_tools.parameter_enum_invalid')
    field('custom_tools.parameter_enum', '["a","b"]')
    field('custom_tools.parameter_minLength', '10')
    field('custom_tools.parameter_maxLength', '2')
    await apply()
    expect(screen.getByRole('alert')).toHaveTextContent('custom_tools.parameter_range_invalid')
    await userEvent.click(screen.getByRole('button', { name: 'custom_tools.parameter_cancel' }))
    await userEvent.click(screen.getByRole('button', { name: 'common.confirm' }))
    expect(changed).not.toHaveBeenCalled()
  })
  it('uses source for composed types and protects reference targets on delete', async () => {
    render(<Harness schema={{ ...simple, properties: { ...simple.properties, copy: { $ref: '#/properties/title' } } }} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.delete title' }))
    expect(notice.error).toHaveBeenCalledWith('custom_tools.parameter_references', { id: 'tool-parameter-error' })
    expect(screen.getByText('title')).toBeVisible()
    await userEvent.click(screen.getByRole('button', { name: 'settings.file_source copy' }))
    expect(sourceValue().properties.copy).toEqual({ $ref: '#/properties/title' })
  })
  it('saves parameter changes with the tool and does not persist while editing', async () => {
    const save = vi.fn().mockResolvedValue(undefined)
    render(<CustomToolEditor initialSection="parameters" tool={{ ...customToolDefaults, id: 'example', name: 'example', description: 'Example tool', inputSchema: simple }} onSave={save} onClose={vi.fn()} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.edit title' }))
    field('custom_tools.parameter_name', 'heading')
    await apply()
    expect(save).not.toHaveBeenCalled()
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(save).toHaveBeenCalledWith(expect.objectContaining({ inputSchema: { ...simple, properties: { heading: simple.properties.title }, required: ['heading'] } }))
  })
  it('blocks tool save while a deletion is being validated', async () => {
    let resolve!: () => void
    validateSchema.mockImplementationOnce(() => new Promise<void>(done => { resolve = done }))
    const save = vi.fn().mockResolvedValue(undefined)
    render(<CustomToolEditor initialSection="parameters" tool={{ ...customToolDefaults, id: 'example', name: 'example', description: 'Example', inputSchema: simple }} onSave={save} onClose={vi.fn()} />)
    await userEvent.click(screen.getByRole('button', { name: 'common.delete title' }))
    expect(screen.getByRole('button', { name: 'common.save' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'common.cancel' })).toBeDisabled()
    await act(async () => resolve())
    await userEvent.click(screen.getByRole('button', { name: 'common.save' }))
    expect(save).toHaveBeenCalledWith(expect.objectContaining({ inputSchema: { ...simple, properties: {}, required: [] } }))
  })
  it('validates source keyword shapes through the main-process API before switching modes', async () => {
    render(<Harness schema={simple} />)
    await source()
    field('custom_tools.schema', '{"type":"object","required":"wrong"}')
    await userEvent.click(screen.getByRole('radio', { name: 'custom_tools.parameter_form' }))
    expect(validateSchema).toHaveBeenCalledWith({ type: 'object', required: 'wrong' })
    expect(screen.getByRole('radio', { name: 'settings.file_source' })).toBeChecked()
    expect(sourceValue()).toEqual({ type: 'object', required: 'wrong' })
    expect(notice.error).toHaveBeenCalled()
  })
})
